@host=https://localhost:7036

GET {{host}}/account/user/me
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjZhZGNiMmE3LWU2YjItNDg0NS1hYmY0LTc5MTQ3NzY5NmU5NiIsImp0aSI6IjllNWE1M2I0LTRlZmMtNGFlNi04MmUwLWJhOTE5ZTAyMDVkNyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE2OTMyOTc3ODQsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcwMzYiLCJhdWQiOiJVc2VyIn0.AODA-7JHNY5E-G4FEYAufwka7HN61b3xHatv42ECvp3KmbUvvDWr3McyEenNRHmV_Xyl8ph35s9fJycI82N6aA
###

GET {{host}}/account/user/8e42aef3-322b-48a6-a9b1-5dfe9ef9841f